name = "GenLinearAlgebra"
uuid = "2304d612-645f-44c0-913c-a25a709b015d"
authors = ["Jean Michel <jean.michel@imj-prg.fr>"]
version = "0.1.1"

[deps]
Combinat = "a6b051d1-fc4b-4ede-b53e-347fa9fb9a74"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Combinat = "0.0.3, 0.0.4, 0.0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
